find_path(SQLPP11_INCLUDE_DIR NAMES sqlpp11/sqlpp11.h)
mark_as_advanced(SQLPP11_INCLUDE_DIR)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SQLPP11 DEFAULT_MSG SQLPP11_INCLUDE_DIR)
if(SQLPP11_FOUND)
	set(SQLPP11_INCLUDE_DIRS ${SQLPP11_INCLUDE_DIR})
else()
	set(SQLPP11_INCLUDE_DIRS)
endif()
